import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'To Do List',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased bg-gray-100 text-gray-900'>{children}</body>
    </html>
  );
}
