import type { Metadata } from 'next';
import './globals.css';
import ThemeProvider from './ThemeProvider';

export const metadata: Metadata = {
  title: 'To Do List',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='antialiased transition-colors duration-300'>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
